argparse: improve add_argument_group and add_mutually_exclusive_group
python/typeshed pull request #10262
Opened 2023-06-04 22:45 UTC by hauntsaninja

2023-06-04 23:03 UTC, hauntsaninja commented
Oh oops, skimmed past the manual default adding here: https://github.com/python/cpython/blob/27a7d5e1cd5b937d5f164fce572d442672f53065/Lib/argparse.py#L1672

2023-06-05 09:41 UTC, srittau requested changes

2023-06-05 09:41 UTC, srittau commented on stdlib/argparse.pyi
> +        conflict_handler: str,
```suggestion
        prefix_chars: str = ...,
        argument_default: Any = ...,
        conflict_handler: str = ...,
```

2023-06-06 06:27 UTC, srittau approved these changes

2023-06-06 06:27 UTC, merged