Add pexpect stubs
python/typeshed pull request #10300
Opened 2023-06-11 15:16 UTC by OscarCreator

I generate stubs for [pexpect](https://github.com/pexpect/pexpect) but I am not so sure about all types. 
I tried to replace some `Incomplete` by looking in the repo's source an tests but would like some help.

2023-06-12 09:16 UTC, srittau requested changes
Thanks! I did not verify the types against the implementation, but most annotations looks fine. A few remarks below, though.

2023-06-12 09:16 UTC, srittau commented on stubs/pexpect/pexpect/pty_spawn.pyi
> +from typing import AnyStr
`AnyStr` is not an alias for `str | bytes`, which is most likely what you want to use instead below.

2023-06-12 09:16 UTC, srittau commented on stubs/pexpect/pexpect/pty_spawn.pyi
> +    def sendline(self, s: str = ""): ...
```suggestion
    def sendline(self, s: str | bytes = ""): ...
```

2023-06-12 09:16 UTC, srittau commented on stubs/pexpect/pexpect/_async.pyi
> +def repl_run_command_async(repl, cmdlines, timeout: int = -1): ...
Using `@coroutine` doesn't work anymore:

```suggestion
async def expect_async(expecter, timeout: Incomplete | None = None): ...
async def repl_run_command_async(repl, cmdlines, timeout: int = -1): ...
```

This should also get rid of the mypy and pyright failures.

2023-06-12 09:16 UTC, srittau commented on stubs/pexpect/pexpect/pty_spawn.pyi
> +    def kill(self, sig, int) -> None: ...
```suggestion
    def kill(self, sig: int) -> None: ...
```

2023-06-12 09:16 UTC, srittau commented on stubs/pexpect/pexpect/utils.pyi
> +InterruptedError: Incomplete
I think we can just remove this for now. It's just a Python 2 compatibility stub in the implementation, which I'm not sure we need. Alternatively you could import it from builtins:

```python
from builtins import InterruptedError as InterruptedError
```

2023-06-19 18:54 UTC, OscarCreator commented
Hi, do you have any idea why I get `error: Returning Any from function declared to return "spawn"` from mypy_primer?
This is the code from pytest:
```python
def spawn(self, cmd: str, expect_timeout: float = 10.0) -> "pexpect.spawn":
        ...

        child = pexpect.spawn(cmd, logfile=logfile, timeout=expect_timeout)
        self._request.addfinalizer(logfile.close)
        return child # complain is here
```
Is `child` not the `spawn` object? Or am I thinking wrong here?

2023-06-21 12:02 UTC, srittau commented
The new primer hit in pytest is most likely due to the weird way that `pexpect` is imported:

```python
    def spawn(self, cmd: str, expect_timeout: float = 10.0) -> "pexpect.spawn":
        ...
        pexpect = importorskip("pexpect", "3.0")
        ...
        child = pexpect.spawn(cmd, logfile=logfile, timeout=expect_timeout)
        self._request.addfinalizer(logfile.close)
        return child
```

I.e., mypy has no idea that `pexpect` in this context is the `pexpect` module.

2023-06-21 12:03 UTC, merged