fix(redis): improve typing of xadd/xdel
python/typeshed pull request #10531
Opened 2023-08-04 08:22 UTC by sileht

typing copied from
https://redis-py.readthedocs.io/en/stable/commands.html#redis.commands.cluster.RedisClusterCommands.xadd
https://redis-py.readthedocs.io/en/stable/commands.html#redis.commands.cluster.RedisClusterCommands.xdel

2023-08-10 13:37 UTC, sileht commented
> Thank! Have you been able to take a look at the CI failures at all? :)

I fixed the issue.

2023-08-10 14:23 UTC, AlexWaygood requested changes

2023-08-10 14:23 UTC, AlexWaygood commented on stubs/redis/redis/commands/core.pyi
> +    def xdel(self, name: _Key, *ids: str | int | bytes | memoryview): ...
Same issue here, please use `redis.typing.KeyT` instead of `redis.client._Key`

2023-08-10 14:23 UTC, AlexWaygood commented on stubs/redis/redis/commands/core.pyi
> +        name: _Key,
Same issue here

2023-08-10 14:23 UTC, AlexWaygood commented on stubs/redis/redis/commands/core.pyi
> +    async def xdel(self, name: _Key, *ids: str | int | bytes | memoryview): ...
Same issue here

2023-08-16 10:24 UTC, AlexWaygood commented
Hi @sileht, have you had a chance to look at my review comments at all? Shouldn't take long to fix :)

2023-08-19 20:14 UTC, sileht commented
> Hi @sileht, have you had a chance to look at my review comments at all? Shouldn't take long to fix :)

I made the update.

But something bothers me. Why does `_Key` even exists? It's used all over the files but I don't see `Union[bytes, str]` in redis-py documentation, only `Union[bytes, str, memoryview]`.

2023-08-22 12:28 UTC, AlexWaygood approved these changes
Thanks!

> But something bothers me. Why does `_Key` even exists? It's used all over the files but I don't see `Union[bytes, str]` in redis-py documentation, only `Union[bytes, str, memoryview]`.

Not sure. It's possible our annotations here predate the time when redis-py started added and documenting the expected types for various functions, in which case these types might be out of date. Feel free to file a follow-up PR if there are inaccuracies compared to what redis-py states in their docs/inline annotations :)

2023-08-22 12:28 UTC, merged