[requests] loosen HTTPError constructor
python/typeshed pull request #10776
Opened 2023-09-25 19:37 UTC by hsheth2

2023-09-26 10:16 UTC, srittau requested changes
Thanks, we need one more change.

2023-09-26 10:16 UTC, srittau commented on stubs/requests/requests/exceptions.pyi
>      request: Request | PreparedRequest
We also need to add `None` to `request`.

2023-09-26 18:26 UTC, hsheth2 commented on stubs/requests/requests/exceptions.pyi
>      request: Request | PreparedRequest
```suggestion
    request: Request | PreparedRequest | None
```

2023-09-27 06:02 UTC, srittau approved these changes
Thanks!

2023-09-27 06:02 UTC, merged