gh-10906: make Any a class on 3.11+
python/typeshed pull request #10908
Opened 2023-10-18 17:51 UTC by graingert

Fixes #10906

2023-10-18 21:07 UTC, Avasam commented on stdlib/typing.pyi
> +    class Any:
This ought to fix your stubtest metaclass issue:
```suggestion
    class _AnyMeta(type): ...
    class Any(metaclass=_AnyMeta):
```

2023-10-18 22:29 UTC, Avasam commented
The last stubtest issue would be resolved by adding `Any.__new__`'s definition. However I'm not entirely certain how to type it. I'm guessing `def __new__(cls, *args: object, **kargs: object) -> Self: ...`. But I'm curious if we can somehow represent that `TypeError` statically.

Anyway mypy seems happy from the mypy_primer results. "new" ibis issues are mostly rewords of a symbol name conflict.
pyright however, really isn't happy about this change, good luck with that! ^^"

2023-10-19 09:49 UTC, srittau commented
The primer hits are interesting. This seems to fix some type annotations where `Any` is used as a type, like in hydra_zen:

https://github.com/mit-ll-responsible-ai/hydra-zen/blob/main/src/hydra_zen/structured_configs/_utils.py

```python
def sanitized_type(...) -> type:
    ...
    return Any
    ...

```

Or in pydantic (https://github.com/pydantic/pydantic/blob/main/pydantic/_internal/_generate_schema.py):

```python
def _generate_parameter_schema(self, ..., annotation: type[Any], ...): ...

def _callable_schema(...):
    ...
    if ...:
        annotation = Any
    else:
        annotation = type_hints[name]
    ....
    self._generate_parameter_schema(..., annotation, ...)
```

2023-10-19 13:57 UTC, JelleZijlstra commented
The `type` return annotation in hydra-zen is simply incorrect though: they also have a branch that returns a Union (https://github.com/mit-ll-responsible-ai/hydra-zen/blob/cfa9f37175eeab39f2a1f52754c58391947c0ccb/src/hydra_zen/structured_configs/_utils.py#L337), which isn't a `type`.

2023-10-20 19:51 UTC, hauntsaninja requested changes
I don't think we should do this. Any is still conceptually very much a special form.

In the past, we've been quite happy to not try to reflect implementation when it comes to special objects in typing.py and I think that has been a good policy (here's a mypy issue from yesterday as a reminder of why this is fraught https://github.com/python/mypy/issues/16297 ). If we do want to make a change like this, we should clarify exactly what behaviour we expect from type checkers, when targeting which versions of Python. If we're unable to decide, status quo should win since it is significantly easier to reason about.

2023-10-28 14:41 UTC, closed without merging