psycopg2: fix RangeCaster.__init__ annotation
python/typeshed pull request #11071
Opened 2023-11-26 16:39 UTC by exg

The pgrange and pyrange arguments should be a string or a class object derived from RangeAdapter and Range, respectively. See

https://github.com/psycopg/psycopg2/blob/2.9.9/lib/_range.py#L313 https://github.com/psycopg/psycopg2/blob/2.9.9/lib/_range.py#L330

2023-11-26 20:19 UTC, hamdanal requested changes
Nice catch.
The type of the `pyrange` parameter of the `register_range` function 20 lines above also needs to be updated.

2023-11-26 21:07 UTC, exg commented
> Nice catch. The type of the `pyrange` parameter of the `register_range` function 20 lines above also needs to be updated.

Fixed, thanks.

2023-11-26 21:37 UTC, hamdanal approved these changes

2023-11-27 07:40 UTC, srittau approved these changes
Thanks!

2023-11-27 07:41 UTC, merged