move re.error into re.pyi
python/typeshed pull request #11188
Opened 2023-12-20 00:12 UTC by tungol

implementation is in sre\_constants / re.\_constants, but it sets it's \_\_module\_\_ to re

2023-12-20 11:12 UTC, srittau approved these changes

2023-12-20 11:14 UTC, srittau requested changes

2023-12-20 11:14 UTC, srittau commented on stdlib/re.pyi
> +class error(Exception):
It's probably best to leave a comment here:

```suggestion
# Defined in module sre_constants in the implementation, but __module__ is overwritten to say re.error.
class error(Exception):
```

Or maybe worded better.

2023-12-23 05:34 UTC, tungol commented
I'm making this a draft pending discussion in https://github.com/python/typeshed/issues/11141

I'm inclined to think using an explicit __module__ attribute (like runtime does) is a better way to handle this discrepancy.

2024-10-02 01:43 UTC, JelleZijlstra approved these changes

2024-10-02 09:26 UTC, srittau approved these changes

2024-10-02 09:26 UTC, merged