Add more networkx annotations for networkx.algorithms.dag
python/typeshed pull request #11224
Opened 2024-01-03 00:05 UTC by wwade

The stubs for this module are now complete with this change.

2024-01-04 11:22 UTC, srittau commented
Thanks! I haven't reviewed the stubs yet, but if networkx is complete, you should be able to remove it from `pyrightconfig.stricter.json` and remove `partial_stub` and `ignore_missing_stub` from the `METADATA.toml` file.

2024-01-04 17:35 UTC, wwade commented
> Thanks! I haven't reviewed the stubs yet, but if networkx is complete, you should be able to remove it from `pyrightconfig.stricter.json` and remove `partial_stub` and `ignore_missing_stub` from the `METADATA.toml` file.

Sorry, the description might have been misleading. Only the `networkx.algorithms.dag`, not all of `networkx`.

2024-01-14 13:00 UTC, srittau requested changes
Thanks! I noticed one thing below.

2024-01-15 17:52 UTC, srittau approved these changes

2024-01-15 17:52 UTC, merged