improve type annotations in 'docutils.core'
python/typeshed pull request #11559
Opened 2024-03-10 07:21 UTC by danieleades

2024-03-12 05:44 UTC, JelleZijlstra commented on stubs/docutils/docutils/core.pyi
> +        source_class: type[Input[_S]] = io.FileInput,
There's some mypy errors about this. It's probably difficult to get this right without overloads.

2024-03-14 13:51 UTC, srittau requested changes
Thanks, a few remarks below.

2024-03-14 13:51 UTC, srittau commented on stubs/docutils/docutils/core.pyi
> +        description: Any | None = None,
Typed wrong in optparse: #11599

```suggestion
        usage: str | None = None,
        description: str | None = None,
```

2024-03-14 13:51 UTC, srittau commented on stubs/docutils/docutils/core.pyi
> +        description: Any | None = None,
```suggestion
        usage: str | None = None,
        description: str | None = None,
```

2024-03-14 13:51 UTC, srittau commented on stubs/docutils/docutils/core.pyi
> +        description: Any | None = None,
```suggestion
        usage: str | None = None,
        description: str | None = None,
```

2024-03-14 13:51 UTC, srittau commented on stubs/docutils/docutils/core.pyi
> +        description: Any | None = None,
```suggestion
        usage: str | None = None,
        description: str | None = None,
```

2024-03-14 13:51 UTC, srittau commented on stubs/docutils/docutils/core.pyi
> +    settings_overrides: Any | None = None,
Could probably be typed. Docstring says:

> `settings_overrides`: A dictionary containing application-specific settings defaults that override the defaults of other components. [...]

Without looking at the source, this this probably a `dict`, `Mapping`, or one of the protocols from `_typeshed`. It's okay to leave it as `Incomplete` now, though.

Applies to all the functions below as well.

2024-03-14 13:51 UTC, srittau commented on stubs/docutils/docutils/core.pyi
> +) -> Any: ...
I'd add a comment to this and the other return types below that this is either `str` or `bytes`.

2024-12-28 04:43 UTC, JelleZijlstra commented
This has a huge merge conflict; do we still need this PR?

2024-12-28 15:40 UTC, closed without merging