Make email.message.Message generic over the header type
python/typeshed pull request #11732
Opened 2024-04-08 10:06 UTC by srittau

2024-04-08 11:22 UTC, srittau commented
The email/http `Message`/`Header` class hierarchy is quite "creative".

2024-04-16 20:38 UTC, Avasam requested changes
A small adjustment for a comment mentioning the Any trick, otherwise this looks good to me.

2024-04-16 20:38 UTC, Avasam commented on stdlib/email/message.pyi
> +    def __getitem__(self, name: str) -> _HeaderT: ...
According to the above comment, this should maybe be using "the Any trick"?

```suggestion
    def __getitem__(self, name: str) -> _HeaderT | Any: ...
```

2024-04-16 20:38 UTC, Avasam commented on stdlib/email/message.pyi
>      # *but* `_HeaderType` itself is currently an alias to `Any`...
(see other comment, github wouldn't let me do a suggestion across a deleted line)
```suggestion
```
```suggestion
    # so using "the Any trick" instead.
```
On that note, we never ended up making an alias for it, something like `MaybeNone`. https://github.com/python/typeshed/issues/11094

2024-04-23 15:39 UTC, Avasam approved these changes

2024-04-23 15:41 UTC, merged