Added types for atheris
python/typeshed pull request #12462
Opened 2024-07-30 14:20 UTC by radarhere

Adding types for https://github.com/google/atheris

2024-08-27 03:54 UTC, radarhere commented
Let me know if there is any further work that would help this progress.

2024-08-29 15:04 UTC, srittau reviewed
Thanks! A quick note: We now require a short comment, explaining why `Any` is necessary. Could you add them?

2024-08-30 02:42 UTC, radarhere commented
Sure. I've added a comment for one, and figured out alternatives for the others.

2024-08-30 11:51 UTC, srittau requested changes
Thanks! I didn't compare to the implementation, but apart from the things below, everything looks reasonable.

2024-08-30 11:51 UTC, srittau commented on stubs/atheris/atheris/utils.pyi
> +    def __init__(self, stream: IO[str], total_count: int) -> None: ...
`IO` and other concrete classes should be avoided in argument annotations. This protocol should work instead:

```python
@type_check_only
class _Writer(Protocol):
    def isatty(self) -> bool: ...
    def write(self, content: bytes, /) -> object: ...
    def flush(self) -> object: ...
```

2024-08-30 11:51 UTC, srittau commented on stubs/atheris/atheris/version_dependent.pyi
> +REVERSE_CMP_OP: list[int]
These constants should all probably marked `Final`.

2024-08-30 12:36 UTC, srittau approved these changes

2024-08-30 12:36 UTC, merged

2024-08-30 12:36 UTC, srittau commented
I'm sorry for the long delay before we managed to review and merge it.

2024-08-30 12:37 UTC, radarhere commented
No worries, I understand there are many other PRs that come in.

Thanks very much