Add stubs for `python-http-client`
python/typeshed pull request #12626
Opened 2024-09-08 02:33 UTC by ajimenez2712

Stubs for https://github.com/sendgrid/python-http-client.

2024-09-08 10:45 UTC, srittau requested changes
Thanks. I suggest to add a few `Final`s (see below.)

2024-09-08 10:45 UTC, srittau commented on stubs/python-http-client/python_http_client/__init__.pyi
> +__version__: str
```suggestion
dir_path: Final[str]
__version__: Final[str]
```

(Needs import from `typing`.)

2024-09-08 10:45 UTC, srittau commented on stubs/python-http-client/python_http_client/client.pyi
> +    methods: set[str]
```suggestion
    methods: Final[set[str]]
```

2024-09-08 10:45 UTC, srittau commented on stubs/python-http-client/python_http_client/exceptions.pyi
> +err_dict: dict[int, type[HTTPError]]
```suggestion
err_dict: Final[dict[int, type[HTTPError]]]
```

2024-09-08 22:52 UTC, ajimenez2712 commented
> Thanks. I suggest to add a few `Final`s (see below.)

Thanks for the review, I already made all suggested changes.

2024-09-09 03:08 UTC, srittau approved these changes

2024-09-09 03:08 UTC, merged