add lupa stubs
python/typeshed pull request #12650
Opened 2024-09-12 19:18 UTC by RedContritio

- add stubs for [lupa](https://pypi.org/project/lupa/)

2024-09-15 13:22 UTC, srittau requested changes
Thanks! A few remarks below. Also, whenever using `Any`, it should be documented why `Any` is necessary and what the possible types are.

2024-09-15 13:22 UTC, srittau commented on stubs/lupa/lupa/lua51.pyi
> +LUA_VERSION: tuple[int, int]
These should probably be `Final`:

```suggestion
LUA_MAXINTEGER: Final[int]
LUA_MININTEGER: Final[int]
LUA_VERSION: Final[tuple[int, int]]
```

(Needs import from `typing`.)

2024-09-15 13:22 UTC, srittau commented on stubs/lupa/lupa/lua51.pyi
> +class _LuaObject: ...
I these are not available at runtime, they should be annotated with `@type_check_only` (from `typing`). Same below.

2024-09-15 13:22 UTC, srittau commented on stubs/lupa/lupa/version.pyi
> +__version__: str
```suggestion
__version__: Final[str]
```

2024-09-15 16:59 UTC, RedContritio commented
> Thanks! A few remarks below. Also, whenever using `Any`, it should be documented why `Any` is necessary and what the possible types are.

I have removed almost all `Any`s, except for `Callable[..., Any]` used in decorators to represent arbitrary functions and `*args: Any, **kwargs: Any` used in variable arguments.

2024-09-16 07:13 UTC, srittau approved these changes

2024-09-16 07:13 UTC, merged