add stubs for m3u8
python/typeshed pull request #12683
Opened 2024-09-21 09:22 UTC by DinhHuy2010

2024-09-23 10:30 UTC, srittau reviewed
Thanks. Not a full review, just a few things I noticed.

2024-09-23 10:30 UTC, srittau commented on stubs/m3u8/m3u8/httpclient.pyi
> +    # return a urllib.request.HTTPSHandler
Redundant comment.

2024-09-24 11:59 UTC, DinhHuy2010 commented on stubs/m3u8/@tests/stubtest_allowlist.txt
> +m3u8.parser.CustomTagsParser
Does that mean I should remove the lines?

2024-09-24 12:01 UTC, DinhHuy2010 commented on stubs/m3u8/m3u8/httpclient.pyi
> +    # return a urllib.request.HTTPSHandler
comment removed

2024-09-24 12:01 UTC, DinhHuy2010 commented on stubs/m3u8/m3u8/httpclient.pyi
> +class HTTPSHandler(urllib.request.HTTPSHandler):
derive from HTTPSHandler removed

2024-09-24 12:14 UTC, srittau commented on stubs/m3u8/@tests/stubtest_allowlist.txt
> +m3u8.parser.CustomTagsParser
Yes, I suspect that if you don't you'd get warnings after changing `CustomTagsParser`.

2024-09-24 12:36 UTC, DinhHuy2010 commented on stubs/m3u8/@tests/stubtest_allowlist.txt
> +m3u8.parser.CustomTagsParser
ok

2024-09-24 12:43 UTC, DinhHuy2010 commented
help me
output:
```text
Running pre-commit...
trim trailing whitespace.................................................Passed
fix end of files.........................................................Passed
check yaml...........................................(no files to check)Skipped
check toml...............................................................Passed
check for merge conflicts................................................Passed
mixed line ending........................................................Passed
check for case conflicts.................................................Passed
Run ruff on stubs, tests and scripts.....................................Passed
Run ruff on the test cases...........................(no files to check)Skipped
black....................................................................Failed
- hook id: black
- files were modified by this hook

reformatted stubs\m3u8\m3u8\httpclient.pyi

All done! ✨ 🍰 ✨
1 file reformatted, 7 files left unchanged.

flake8...................................................................Passed
Check hooks apply to the repository..................(no files to check)Skipped

Running check_typeshed_structure.py...

Running Pyright (stricter configs) for Python 3.8...
10.8.3
Running: C:\Program Files\nodejs\npx.CMD pyright@1.1.381 .\stubs\m3u8\ 
--pythonversion 3.8 -p pyrightconfig.stricter.json
0 errors, 0 warnings, 0 informations 


Running mypy for Python 3.8...
*** Testing Python 3.8 on win32
Testing third-party packages...
testing m3u8 (8 files)... success

--- success, 8 files checked ---

Running stubtest...
m3u8... Note: m3u8 is not currently tested on win32 in typeshed's CI.
fail

********************************************************************** 

Commands run:

C:\Users\DINHHU~1\AppData\Local\Temp\tmp6_zwnlhd\Scripts\pip.exe install m3u8[]==6.0.* mypy==1.11.1
MYPYPATH=D:\.gitdev\typeshed\stubs\m3u8 C:\Users\DINHHU~1\AppData\Local\Temp\tmp6_zwnlhd\Scripts\python.exe -m mypy.stubtest --custom-typeshed-dir D:\.gitdev\typeshed m3u8 --allowlist stubs\m3u8\@tests\stubtest_allowlist.txt

********************************************************************** 

Command output:

error: m3u8.load is inconsistent, runtime argument "http_client" has a 
default value of type m3u8.httpclient.DefaultHTTPClient, which is incompatible with stub argument type m3u8.httpclient._HTTPClientProtocol    
Stub: in file D:\.gitdev\typeshed\stubs\m3u8\m3u8\__init__.pyi:67      
def (uri: builtins.str, timeout: Union[Any, None] =, headers: typing.Mapping[builtins.str, Any] =, custom_tags_parser: Union[def (builtins.str, builtins.int, builtins.dict[builtins.str, Any], builtins.dict[builtins.str, Any]) -> builtins.object, None] =, http_client: m3u8.httpclient._HTTPClientProtocol =, verify_ssl: builtins.bool =) -> m3u8.model.M3U8 
Runtime: in file C:\Users\DINHHU~1\AppData\Local\Temp\tmp6_zwnlhd\Lib\site-packages\m3u8\__init__.py:81
def (uri, timeout=None, headers={}, custom_tags_parser=None, http_client=<m3u8.httpclient.DefaultHTTPClient object at 0x0000012D8048E910>, verify_ssl=True)

error: m3u8.httpclient.DefaultHTTPClient.download is not present in stub
Stub: in file D:\.gitdev\typeshed\stubs\m3u8\m3u8\httpclient.pyi       
MISSING
Runtime: in file C:\Users\DINHHU~1\AppData\Local\Temp\tmp6_zwnlhd\Lib\site-packages\m3u8\httpclient.py:11
def (self, uri, timeout=None, headers={}, verify_ssl=True)

error: m3u8.model.CustomTagsParser is not present at runtime
Stub: in file D:\.gitdev\typeshed\stubs\m3u8\m3u8\model.pyi:12
Type alias for def (builtins.str, builtins.int, builtins.dict[builtins.str, Any], builtins.dict[builtins.str, Any]) -> builtins.object        
Runtime:
MISSING

error: m3u8.parser.CustomTagsParser is not present at runtime
Stub: in file D:\.gitdev\typeshed\stubs\m3u8\m3u8\parser.pyi:7
Type alias for def (builtins.str, builtins.int, builtins.dict[builtins.str, Any], builtins.dict[builtins.str, Any]) -> builtins.object        
Runtime:
MISSING

note: unused allowlist entry m3u8._CustomTagsParser
note: unused allowlist entry m3u8.model._CustomTagsParser
note: unused allowlist entry m3u8.parser._CustomTagsParser
Found 7 errors (checked 8 modules)

********************************************************************** 

Python version: Python 3.11.8 (tags/v3.11.8:db85d51, Feb  6 2024, 22:03:32) [MSC v.1937 64 bit (AMD64)]

Ran with the following environment:
m3u8==6.0.0
mypy==1.11.1
mypy-extensions==1.0.0
pip==24.2
setuptools==75.1.0
typing_extensions==4.12.2
wheel==0.44.0

********************************************************************** 

To fix "unused allowlist" errors, remove the corresponding entries from stubs\m3u8\@tests\stubtest_allowlist.txt


********************************************************************** 

Upstream repository: https://github.com/globocom/m3u8
Typeshed source code: https://github.com/python/typeshed/tree/main/stubs/m3u8

********************************************************************** 


Running pytype...
Testing files with pytype...
Ran pytype with 8 pyis, got 0 errors.

Regression tests: No test_cases folder for 'm3u8'!


--- TEST SUMMARY: One or more tests failed. See above for details. --- 

pre-commit Failed
  Check the output of pre-commit for more details.
  This could mean that there's a lint failure on your code,
  but could also just mean that one of the pre-commit tools
  applied some autofixes. If the latter, you may want to check
  that the autofixes did sensible things.
Check structure: Success
Pyright: Success
mypy: Success
stubtest: Failed
pytype: Success
Pyright regression tests: Success
mypy regression test: Success
```
![image](https://github.com/user-attachments/assets/4fd0a461-5efa-41fe-b8cc-0d5eeb42abb3)
![image](https://github.com/user-attachments/assets/ab3dcb65-42a7-4296-bcb9-2dcda859d05f)

2024-09-24 15:49 UTC, DinhHuy2010 commented on stubs/m3u8/m3u8/__init__.pyi
> +__all__ = [
what does that mean???

2024-09-24 17:26 UTC, srittau commented on stubs/m3u8/m3u8/__init__.pyi
> +]
```suggestion
__all__ = (
    "M3U8",
    "Segment",
    "SegmentList",
    "PartialSegment",
    "PartialSegmentList",
    "Key",
    "Playlist",
    "IFramePlaylist",
    "Media",
    "MediaList",
    "PlaylistList",
    "Start",
    "RenditionReport",
    "RenditionReportList",
    "ServerControl",
    "Skip",
    "PartInformation",
    "PreloadHint",
    "DateRange",
    "DateRangeList",
    "ContentSteering",
    "ImagePlaylist",
    "Tiles",
    "loads",
    "load",
    "parse",
    "ParseError",
)
```

2024-09-24 17:34 UTC, JelleZijlstra commented on stubs/m3u8/m3u8/__init__.pyi
> +__all__ = [
Define `__all__` as a tuple, like `__all__ = ("a", "b")`, instead of a list like `__all__ = ["a", "b"]`.

2024-09-25 11:41 UTC, DinhHuy2010 commented on stubs/m3u8/m3u8/__init__.pyi
> +]
changed

2024-09-25 11:42 UTC, DinhHuy2010 commented on stubs/m3u8/m3u8/__init__.pyi
> +__all__ = [
just fix that, thanks!

2024-09-30 13:45 UTC, srittau requested changes
Thanks! A few notes below. Also, please either add a short comment explaining the allowed types for each `Any` or change the `Any`s to `Incomplete` for now.

2024-09-30 13:45 UTC, srittau commented on stubs/m3u8/m3u8/mixins.pyi
> +class BasePathMixin(Protocol):
As this is not a protocol at runtime, it shouldn't be a protocol here either.

2024-09-30 13:45 UTC, srittau commented on stubs/m3u8/m3u8/model.pyi
> +    base_uri: str | None
To make this then work correctly, it should be changed to:

```suggestion
@type_check_only
class _PlaylistProtocol(Protocol):
    base_uri: str | None
    uri: str | None
    @property
    def absolute_uri(self) -> str: ...
    @property
    def base_path(self) -> str: ...
    @base_path.setter
    def base_path(self, newbase_path: str) -> None: ...
    def get_path_from_uri(self) -> str: ...
```

2024-10-01 10:25 UTC, DinhHuy2010 commented
got this error on changing
![image](https://github.com/user-attachments/assets/6e7c7ba1-6048-4633-836f-a10fe4bb64a0)

2024-10-01 10:29 UTC, srittau commented
You should remove the `# type: ignore` from the first line and see what happens. We don't really use module-level ignores in typeshed anyway.

2024-10-01 10:32 UTC, DinhHuy2010 commented
no error from mypy

2024-10-01 12:05 UTC, srittau approved these changes

2024-10-01 12:05 UTC, merged