Add geopandas stubs
python/typeshed pull request #12990
Opened 2024-11-10 14:35 UTC by hamdanal

These are basically copied over from [hamdanal/python-stubs](https://github.com/hamdanal/python-stubs/tree/0d49251f97c37ada4c837fb3479969bd0865b4e6/stubs/geopandas-stubs). I've been using them for a while with Pylance and fixing them along the way, hopefully they are of good quality. I've also written some tests in the original repo that I did not include in the PR but might consider using some of them later if we find it necessary.

2024-11-10 15:23 UTC, hamdanal commented
Not sure about the stub uploader failure. It is complaining about pandas-stubs while it should be complaining about pyproj.

2024-11-11 12:33 UTC, hamdanal commented
Looks like stub_uploader is checking if pandas-stubs is a dependency of the runtime package instead of checking for pandas. @srittau do you think we can change stub_uploader to look for pandas in the runtime dependencies whenever it sees pandas-stubs used in a typeshed typing package?

2024-11-25 17:14 UTC, srittau commented
CI now passes.

2024-11-25 20:03 UTC, hamdanal commented
This is now ready for review

2025-01-19 13:57 UTC, srittau requested changes
Thanks, I've noticed quite a few uncommented `Any`s. Please note that we now require each `Any` to be documented with the possible types or the reason why `Any` is necessary. In the case of `dict[str, Any]` it could sometimes be better to use `dict[str, Incomplete]` if it might be possible to convert the dict to a `TypedDict`.

2025-01-19 13:57 UTC, srittau commented on stubs/geopandas/geopandas/explore.pyi
> +from matplotlib.colors import Colormap  # type: ignore[import-not-found]
We usually declared a type alias for this, e.g.:

```python
Colormap: TypeAlias = Any  # from matplotlib.colors
```
But I'm actually interested how well this approach works.

2025-01-19 14:12 UTC, hamdanal commented on stubs/geopandas/geopandas/explore.pyi
> +from matplotlib.colors import Colormap  # type: ignore[import-not-found]
It works very well in this case because these imports usage is localized to places where the optional dependency would be present at runtime, so there is no confusion for type checkers.

2025-01-19 14:59 UTC, hamdanal commented
> Thanks, I've noticed quite a few uncommented `Any`s. Please note that we now require each `Any` to be documented with the possible types or the reason why `Any` is necessary. In the case of `dict[str, Any]` it could sometimes be better to use `dict[str, Incomplete]` if it might be possible to convert the dict to a `TypedDict`.

Thanks for the review. I replaced some `Any`s by `Incomplete`s and commented on all the remaining ones.

2025-01-19 18:19 UTC, srittau approved these changes

2025-01-19 18:19 UTC, merged