add `types.GenericAlias.__mro_entries__`
python/typeshed pull request #13284
Opened 2024-12-23 07:19 UTC by tungol

I used `Iterable[object]` because it matches the call signature of `resolve_bases`, but it could just as easily be `Any` because the specific implementation here doesn't look at the argument and always returns a 1-tuple of the `__origin__` attribute.

2024-12-23 20:13 UTC, tungol commented
steam.py has a custom subclass of GenericAlias which defines a `__mro_entries__` as `def __mro_entries__(self, bases: tuple[type, ...]) -> tuple[type]:`. That's what I probably would have gone with here myself if I hadn't seen the discussion for `types.resolve_bases`.

2025-01-13 13:56 UTC, srittau requested changes

2025-01-13 13:56 UTC, srittau commented on stdlib/types.pyi
> +        def __mro_entries__(self, bases: Iterable[object], /) -> tuple[type]: ...
```suggestion
        def __mro_entries__(self, bases: Iterable[object], /) -> tuple[type, ...]: ...
```

2025-01-13 18:35 UTC, tungol commented on stdlib/types.pyi
> +        def __mro_entries__(self, bases: Iterable[object], /) -> tuple[type]: ...
Actually, it is always a 1-tuple: https://github.com/python/cpython/blob/b70a567575db37846beecbe8b40fb56b875274db/Objects/genericaliasobject.c#L642

2025-01-13 19:45 UTC, srittau commented on stdlib/types.pyi
> +        def __mro_entries__(self, bases: Iterable[object], /) -> tuple[type]: ...
While that's true for `GenericAlias`, the `__mro_entries__` protocol allows any length. I'd prefer to hide this implementation detail and use the defined protocol, instead.

2025-01-15 14:35 UTC, srittau approved these changes
Thanks!

2025-01-15 14:36 UTC, merged