Add more stubs for redis-py
python/typeshed pull request #4557
Opened 2020-09-18 06:16 UTC by brainix

I've tested these stubs against my own project here:
https://github.com/brainix/pottery/pull/240

The output is clean for all these new stubs when running `$ mypy
--strict`.

2020-09-18 09:37 UTC, srittau requested changes
Thanks, two remarks below.

2020-09-18 09:37 UTC, srittau commented on third_party/2and3/redis/client.pyi
> +    def srandmember(self, name: _Key, number: Optional[int] = ...) -> _Value: ...
This returns `Optional[_Value]` if `number` is not given or is `None` and a list of values if `number` is not `None`. We should use overloads to reflect this.

2020-09-18 09:37 UTC, srittau commented on third_party/2and3/redis/client.pyi
> +    def setex(self, name: _Key, time: Union[int, timedelta], value: _Value): ...
Returns `bool`.

2020-09-20 03:36 UTC, brainix commented
Hi, @srittau.

Thanks for the feedback; I believe I've addressed your concerns. However, now, whenever I run `$ mypy --strict`, one of the errors that I get is:

2020-09-20 04:00 UTC, brainix commented
Thanks for the feedback, @srittau. I believe that I've addressed your concerns. How does this Pull Request look now?

2020-09-21 12:33 UTC, srittau commented on third_party/2and3/redis/client.pyi
> +    def srandmember(self, name: _Key, number: int) -> List[_Value]: ...
One little thing and then this is ready to go. The first overload needs `number: None = ...` as `srandmember()` has a default (`None`) for the second argument.

2020-09-21 13:15 UTC, srittau approved these changes

2020-09-21 13:38 UTC, merged