tarfile: use the same _DirT type as tempfile.
python/typeshed pull request #4569
Opened 2020-09-22 14:45 UTC by Flameeyes

This allows all of parameters that rely on os.path functions, or the builtin
open() to take os.PathLike objects as well.

2020-09-22 16:25 UTC, JelleZijlstra requested changes
I'm not sure I understand this change. Your `_DirT` seems to boil down to just Any, and the previous `AnyPath` already made it so we accept both str and PathLike.

On a quick look it appears that none of what this PR proposes is necessary.

2020-09-22 16:25 UTC, JelleZijlstra commented on stdlib/2and3/tarfile.pyi
> +_S = TypeVar("_S")
Looks unused

2020-09-22 16:25 UTC, JelleZijlstra commented on stdlib/2and3/tarfile.pyi
> +if sys.version_info >= (3, 6):
You only use this in argument positions, so why do you need the typevar?

2020-09-25 11:32 UTC, Flameeyes commented
> I'm not sure I understand this change. Your `_DirT` seems to boil down to just Any, and the previous `AnyPath` already made it so we accept both str and PathLike.

Seems like `AnyPath` doesn't quite do that:

```
# example.py
import pathlib
import tarfile

t = tarfile.open('output.tgz', mode='w:gz')
t.add(pathlib.Path.cwd())
t.add(1)
```

```
flameeyes@seleya:~/test-pathlib-tarfile> mypy example.py 
example.py:5: error: Argument 1 to "add" of "TarFile" has incompatible type "Path"; expected "str"
example.py:6: error: Argument 1 to "add" of "TarFile" has incompatible type "int"; expected "str"
Found 2 errors in 1 file (checked 1 source file)
flameeyes@seleya:~/test-pathlib-tarfile> mypy --custom-typeshed-dir ~/devel/repos/typeshed example.py 
example.py:6: error: Argument 1 to "add" of "TarFile" has incompatible type "int"; expected "Union[str, _PathLike[str]]"
Found 1 error in 1 file (checked 1 source file)
```

But I do grant you that this pull request is rough around the edges, I was copying it from tempfile, and I got pretty much lost myself on what needs to happen.

2020-09-25 11:35 UTC, JelleZijlstra commented
Note that we only recently changed TarFile.add to accept Path (https://github.com/python/typeshed/commit/7894269bb5ed3dd5478d2cdd7103707097434cbe#diff-c5e600e82cf48a71883c58ac4e3fe567)—I think that's not made it into a mypy release yet.

2020-09-25 11:37 UTC, Flameeyes commented
> Note that we only recently changed TarFile.add to accept Path ([7894269#diff-c5e600e82cf48a71883c58ac4e3fe567](https://github.com/python/typeshed/commit/7894269bb5ed3dd5478d2cdd7103707097434cbe#diff-c5e600e82cf48a71883c58ac4e3fe567) )—I think that's not made it into a mypy release yet.

Uh. Yeah that works. Sorry for the noise :(

2020-09-25 11:37 UTC, closed without merging