update requests stubs with various missing methods
python/typeshed pull request #4691
Opened 2020-10-22 08:16 UTC by vbarbaresi

I used the latest `requests==2.24.0` as reference and ran stubtest. I fixed and updated a few things

2020-10-23 10:34 UTC, srittau requested changes
Thanks, remarks below.

2020-10-23 10:34 UTC, srittau commented on third_party/2and3/requests/utils.pyi
> +def get_environ_proxies(url, no_proxy: Iterable[AnyStr] = ...) -> Dict[Any, Any]: ...
There is an explicit `None` check for `no_proxy`.

2020-10-23 10:34 UTC, srittau commented on third_party/2and3/requests/utils.pyi
> +def select_proxy(url, proxies: Dict[Any, Any]): ...
There is this line in the implementation: `proxies = proxies or {}`, so `None` is accepted. Also `Mapping` should be sufficient:

```suggestion
def select_proxy(url: Text, proxies: Optional[Mapping[Any, Any]]): ...
```

2020-10-23 10:34 UTC, srittau commented on third_party/2and3/requests/utils.pyi
> +def check_header_validity(header: Tuple[AnyStr, ...]) -> None: ...
As `header` is a two-element tuple, not an arbitrary sized one:

```suggestion
def check_header_validity(header: Tuple[AnyStr, AnyStr]) -> None: ...
```

2020-10-23 10:36 UTC, srittau commented
We now had a merge conflict with master, which I resolved.

2020-10-24 07:30 UTC, vbarbaresi commented
Thanks for the thorough review and the conflict resolution!
I checked and applied all your suggestions 👌

2020-10-24 12:01 UTC, srittau approved these changes

2020-10-24 12:01 UTC, merged