add type hints for yaml.add_constructor and construct_scalar
python/typeshed pull request #4796
Opened 2020-12-02 11:37 UTC by MrGreenTea

Signed-off-by: Jonas Bulik <jonas@bulik.dev>

2020-12-13 14:31 UTC, hoefling commented
@JelleZijlstra @hauntsaninja @srittau gentle ping - please advise if there's something we can do to make this PR approvable.

2020-12-14 07:18 UTC, JelleZijlstra requested changes

2020-12-14 07:18 UTC, JelleZijlstra commented on third_party/2and3/yaml/constructor.pyi
> +Scalar = Union[Text, int, float, bool, None]
```suggestion
_Scalar = Union[Text, int, float, bool, None]
```
Should be underscore-prefixed because it doesn't exist at runtime.

2021-01-23 19:46 UTC, srittau approved these changes

2021-01-23 19:46 UTC, merged