Added **kw to place/pack/grid_configure #4836
python/typeshed pull request #4874
Opened 2020-12-29 23:28 UTC by melassa

#4836
Added *kw to accept "in" param

2020-12-31 18:42 UTC, Akuli requested changes

2020-12-31 18:42 UTC, Akuli commented on stdlib/3/tkinter/__init__.pyi
> +        **kw: Any,
Stubs typically don't contain much comments, but a comment explaining why there is `**kw` and mentioning the issue number would be useful.

2020-12-31 20:12 UTC, melassa commented
Can you write it? I am a newbie..

2021-01-01 00:26 UTC, Akuli commented
Something like this:

```
 **kw: Any,  # allow keyword argument named 'in', see #4836
```

2021-01-02 12:05 UTC, Akuli approved these changes

2021-01-02 14:03 UTC, merged