Update io.pyi
python/typeshed pull request #4912
Opened 2021-01-06 12:19 UTC by baterflyrity

See corresponding [issue](https://github.com/python/typeshed/issues/4906#issue-779374573).

2021-01-06 16:41 UTC, Akuli commented
Maybe this is related: https://github.com/python/mypy/issues/5876

2021-01-06 16:59 UTC, Akuli requested changes
This should fix the mypy_primer errors. I tried doing what werkzeug does, but I didn't check if other errors get fixed with this.

2021-01-06 16:59 UTC, Akuli commented on stdlib/3/io.pyi
> +    def read(self, *args: Any, **kwargs: Any) -> Any: ...
```suggestion
    read: Callable[..., Any]
    def read(self, *args: Any, **kwargs: Any) -> Any: ...
```

2021-01-06 16:59 UTC, Akuli commented on stdlib/3/io.pyi
> +    def write(self, *args: Any, **kwargs: Any) -> Any: ...
```suggestion
    write: Callable[..., Any]
```

2021-01-06 17:42 UTC, baterflyrity commented
@Akuli , thanks for help. Useful link and commit, hope it will help.

ps
Also one can try for similar issue next links:  [partially arbitrary parameters](https://github.com/python/mypy/issues/5876#issuecomment-706396563) and [property hack](https://github.com/python/mypy/issues/9560#issuecomment-705955103).

2021-01-06 17:58 UTC, Akuli commented
Don't know if mypy_primer is showing outdated results above

2021-01-06 19:57 UTC, baterflyrity commented
@Akuli , so what can you suggest?

2021-01-06 20:19 UTC, Akuli commented
I would try making an empty commit to rerun mypy_primer. Don't know if there's a better way.

2021-01-07 09:48 UTC, baterflyrity commented
@Akuli , very nice, according to [mypy_primer](https://github.com/python/typeshed/pull/4912/checks?check_run_id=1661452668#step:3:324) no diffs found. So what is needed next to merge this PR and close #4906 ?

2021-01-07 11:25 UTC, Akuli commented
A typeshed collaborator (not me, I'm just a contributor) has to review this, and if it looks good to the collaborator, they will likely merge it and close the issue.

2021-01-07 11:25 UTC, Akuli approved these changes

2021-01-08 11:17 UTC, srittau approved these changes
The change seems correct to me and the best solution. I am still a bit wary that this might cause unforeseen problems, but the mypy_primer output makes me optimistic. Let's try this an be prepared to revert if it causes problems.

2021-01-08 11:19 UTC, merged