turtle.pyi: Add functions copied from _Screen
python/typeshed pull request #5104
Opened 2021-03-10 09:58 UTC by krouziciorel

The turtle module re-exports methods of its classes as top-level functions.
Typeshed includes most of these, but `exitonclick` and others from the
`_Screen` class were missing.
Add them.

2021-03-15 19:18 UTC, encukou commented on stdlib/turtle.pyi
> +def setup(width: Union[int, float], height: Union[int, float], startx: Optional[int], starty: Optional[int]) -> None: ...
```suggestion
def setup(
    width: Union[int, float] = ..., height: Union[int, float] = ..., startx: Optional[int] = ..., starty: Optional[int] = ...
) -> None: ...
```

2021-03-17 10:58 UTC, srittau requested changes
Thank you. One minor remark below.

2021-03-17 10:58 UTC, srittau commented on stdlib/turtle.pyi
> +) -> None: ...
```suggestion
def setup(width: float = ..., height: float = ..., startx: Optional[int] = ..., starty: Optional[int] = ...) -> None: ...
```

For type checking purposes, `int` is a sub-type of `float` (per PEP 484). So, `Union[int, float]` is equivalent to just `float`, at least in argument types.

2021-03-19 10:09 UTC, srittau approved these changes

2021-03-19 10:10 UTC, merged