Add python-box stubs
python/typeshed pull request #5140
Opened 2021-03-25 04:39 UTC by JacobHayes

[Box](https://github.com/cdgriffith/Box) is an arbitrarily nested dict that can also be accessed with attribute (".") lookup. A few things make this trickier to type:
- dynamic attribute lookup
- name mangled methods (to prevent shadowing assigned values)
- nesting/[type recursion](https://github.com/python/mypy/issues/731)

I have a minimal set of stubs right now, but wanted to see if this seems like the right approach to take. If there's a way around the name manging issue, I might be able to add type hints upstream/inline if @cdgriffith is open.

2021-04-08 04:50 UTC, JelleZijlstra requested changes
This is missing a number of exported names in the package (https://github.com/cdgriffith/Box/blob/master/box/__init__.py), so it should be marked with a module-level `def __getattr__()` to mark it as incomplete.

There's also some missing dunder methods in the Box class, such as `__add__`. You'll need to add those to the class, because `__getattr__` doesn't cover them (checked here: https://mypy-play.net/?mypy=latest&python=3.9&gist=b96ef5e7327755f4d2de2407d8a494af).

2021-04-08 04:50 UTC, JelleZijlstra commented on stubs/python-box/box.pyi
> +class Box(MutableMapping[str, Union[Any, MutableMapping[str, Any]]]):
```suggestion
class Box(dict[str, Union[Any, MutableMapping[str, Any]]]):
```
It inherits from Dict at runtime, no need to do something different here

2021-06-16 12:52 UTC, JelleZijlstra commented
@JacobHayes are you still interested in moving this forward?

2021-09-11 11:20 UTC, srittau commented
Closing this for now. It can be reopened if you find time to work on this.

2021-09-11 11:20 UTC, closed without merging