Rename _CursesWindow to window
python/typeshed pull request #5180
Opened 2021-04-03 22:04 UTC by rmccampbell

The name `_CursesWindow` is not exposed at runtime which makes explicit type annotation difficult. It has to be wrapped in quotes, and this doesn't seem to work for all type checkers: PyLance's typechecker accepts it but Jedi's doesn't (tested in VS Code). This is especially annoying because with `curses.wrapper(callback)` there is no way to infer the type of the passed window except with an explicit annotation.

Experimentally, the type is exposed under the name `_curses.window` in Python 3.9 on both Ubuntu and Windows (via [windows-curses](https://pypi.org/project/windows-curses/)). While this is not explicitly documented as public, it is the name used for all the method [docs](https://docs.python.org/3/library/curses.html#window-objects), and it is probably unlikely to change since some might interpret the lack of underscore as indicating it is public. Unfortunately it doesn't seem to be exposed as such in Python 2, but `¯\_(ツ)_/¯`. Using the runtime name should allow type checking to work with most typecheckers/platforms without quotes, and the old name can be kept as an alias for backwards compatibility.

2021-04-04 06:17 UTC, rmccampbell commented
Turns out the name _curses.window is only exposed in >= 3.8, so I put the new name behind a version test and reverted to the old name everywhere else.

2021-04-05 18:11 UTC, Akuli requested changes

2021-04-05 18:11 UTC, Akuli commented on stdlib/_curses.pyi
> +    window = _CursesWindow
Can't find it in python docs:

```suggestion
    window = _CursesWindow  # undocumented
```

2021-04-05 18:13 UTC, Akuli commented on stdlib/_curses.pyi
> +    window = _CursesWindow
Specifically, the docs say `window.something`, but seems like that `window` should be interpreted as just a variable name. Also, Python 3.7 docs say `window.something` too, even though it doesn't have `curses.window`.

2021-04-05 20:58 UTC, Akuli approved these changes

2021-04-05 20:59 UTC, merged