Add docutils definitions and (incomplete) modules
python/typeshed pull request #5192
Opened 2021-04-08 12:40 UTC by srittau

2021-04-08 12:56 UTC, srittau commented
python/mypy#10242, cc @rchen152: Could you have a look at the pytype errors? I can't make sense of them. I suspect this is also related to using `tuple[X, ...]`, but I'm not sure.

2021-04-09 00:25 UTC, rchen152 commented
The pytype test failures are caused by pytype assuming that some imports are modules when they're actually classes. I filed https://github.com/google/pytype/issues/882. You should be able to work around this by modifying the imports that pytype is unhappy with like this:

```
stubs/docutils/docutils/frontend.pyi
------------------------------------
-from . import SettingsSpec
+from docutils import SettingsSpec
 
stubs/docutils/docutils/io.pyi
------------------------------
-from . import TransformSpec
+from docutils import TransformSpec
 
 stubs/docutils/docutils/parsers/__init__.pyi
---------------------------------------------
-from .. import Component
+from docutils import Component

stubs/docutils/docutils/parsers/rst/__init__.pyi
--------------------------------------------------
-from ... import parsers
+from docutils import parsers
```

2021-04-16 04:20 UTC, JelleZijlstra requested changes
Thanks! Just two comments

2021-04-16 04:20 UTC, JelleZijlstra commented on stubs/docutils/docutils/io.pyi
> +        mode: Literal["r", "rb"] = ...,
This is the default but not the only possibility; it also allows `rU` in Python 2 at least.

2021-04-16 04:20 UTC, JelleZijlstra commented on stubs/docutils/docutils/io.pyi
> +    mode: ClassVar[Literal["w", "wb"]]
This can also be wider; I guess we can use the aliases from `_typeshed`

2021-04-16 18:50 UTC, merged