tarfile improvements
python/typeshed pull request #5492
Opened 2021-05-18 07:28 UTC by srittau

* Use `Literal` for `mode`.
* Don't explicitly derive from `Iterable`.
* Use imports from `collections.abc`.
* Partialy replace `IO` in `TarFile`.

More `IO` improvements are possible in the future:

* Split into `_ReadableFileobj` and `_WritableFileobj`, depending on `mode`.
* `TarFile.bz2open()` and `.xzopen()` still use `IO`. This depends on improving `bz2.pyi` and `lzma.pyi` respectively gaining protocols.
* `TarFile.open()` and module-level `open()` still use `IO`. This could be improved using overloads.
* Some other functions and methods still use `IO`.

Closes: #5491

2021-05-18 09:45 UTC, srittau commented
GitHub Actions is having issues again. https://www.githubstatus.com/

2021-05-18 20:30 UTC, srittau commented
It passes now.

2021-05-18 20:38 UTC, JelleZijlstra commented
I need more time to look at this properly, but it feels like a shame if we don't switch `tarfile.open` to a protocol, since that's presumably the main API users would use; it's also the API being used in the linked issue.

2021-05-18 20:41 UTC, srittau commented
Good point about this not closing the linked issue. `tarfile.open()` (which is alias of `tarfile.TarFile.open()`) is certainly doable and should be done, but needs may overloads and protocols for `lzma` and `bz2` to be fully typed.

2021-05-18 20:43 UTC, srittau commented
To clarify: If I find time to do more, I'd like to do it in a separate PR. And possibly work on `lzma` and `bz2` first.

2021-05-19 01:41 UTC, JelleZijlstra requested changes
Looks good apart from one detail

2021-05-19 01:41 UTC, JelleZijlstra commented on stdlib/tarfile.pyi
> +    mode: Literal["r", "a", "w"]
Looks like the implementation also allows `"x"`.
```suggestion
    mode: Literal["r", "a", "w", "x"]
```

2021-05-19 08:13 UTC, merged