Pymysql cursor types and fetching return types
python/typeshed pull request #5652
Opened 2021-06-16 18:55 UTC by Akuli

Fixes #5567 so that `Cursor` and `DictCursor` no longer return annoying unions. I also got rid of several `Optional`s. In those methods, I looked at the source code and I tried `select * from foo` on a local test database, and couldn't get it to return `None`.

I also made `Connection` generic, so that when you create a connection, it remembers which cursor class you want to use. You can still customize this by passing a custom class to `.cursor()`.

2021-06-17 11:06 UTC, srittau requested changes
I haven't compared with the implementation, but the changes look reasonable. Especially getting rid of the response unions. Two remarks below.

Also, could you also update the version in `METADATA.toml`?

2021-06-17 11:06 UTC, srittau commented on stubs/PyMySQL/pymysql/connections.pyi
> +        host: Optional[str] = ...,
`str | None` (also below)

2021-06-17 11:06 UTC, srittau commented on stubs/PyMySQL/pymysql/connections.pyi
> +        ssl_verify_identity: Any = ...,
Don't use `Any` here, just leave unannotated, same in the other overload.

2021-06-17 18:52 UTC, srittau approved these changes

2021-06-17 18:53 UTC, merged

2021-07-08 13:31 UTC, Alch-Emi commented
I'm having some problems with this, but I'm posting here instead of creating a new issue in case I'm doing something dumb.  I'm currently writing some typed code that uses a `Connection[Cursor]`, but when I include this in my function signature, I get the error `TypeError: 'type' object is not subscriptable`, presumably since the underlying library doesn't expect `Connection` to be a generic.

I was able to fix this either by patching pymysql to use a generic Connection, or by removing the generic from my type signature.  The former solution of course makes the code much harder to maintain, and would require a fork of pymysql specifically for this project, at least until pymysql adopts python 3.10 or 3.7 (See https://github.com/PyMySQL/PyMySQL/issues/953).  The later causes my typechecker to complain very loudly about how Connection is supposed to be a generic, and also removes the benefit of having the generic in the first place.

Is there a solution to this that doesn't require either leaving a type error in the code or forking pymysql?

2021-07-08 14:02 UTC, Akuli commented
On 3.7+, add to beginning of file:

```python
from __future__ import annotations
```

This tells Python to not evaluate the type annotations, so that they are just for the type checker. It also means that you can also use `Foo | None` instead of `Optional[Foo]`, for example.

2021-07-08 14:31 UTC, Alch-Emi commented
Oh thank you so much!  That's perfect!