Make `NewType` a class in 3.10
python/typeshed pull request #6469
Opened 2021-12-01 18:53 UTC by AlexWaygood

`NewType` was changed in 3.10; it is now a class, rather than a function. https://bugs.python.org/issue44353

2021-12-01 19:36 UTC, AlexWaygood commented
Seems like this breaks pyright.

2021-12-02 00:45 UTC, dfoerster-athene commented
I think the issue is here: https://github.com/python/typeshed/blob/8542b3518a36313af57b13227996168e592fe868/stubs/protobuf/google/protobuf/internal/enum_type_wrapper.pyi#L5. The TypeVar is bound to `int`, but is used instead with the distinct `_Syntax.V` NewType wrapper.

2021-12-02 09:18 UTC, AlexWaygood commented
@erictraut, how tricky would it be to change the way pyright special-cases `NewType`? Would it be better for me to abandon this PR for now?

2021-12-02 18:18 UTC, erictraut commented
@AlexWaygood, it's an easy change. I just implemented it, and it will be included in the next release of pyright (1.1.192). I can publish the new version later today (within the next 12 hours) to unblock your PR. You'd just need to update the CI scripts to point to pyright 1.1.192 as part of your PR.

2021-12-02 18:21 UTC, AlexWaygood commented
> @AlexWaygood, it's an easy change. I just implemented it, and it will be included in the next release of pyright (1.1.192). I can publish the new version later today (within the next 12 hours) to unblock your PR. You'd just need to update the CI scripts to point to pyright 1.1.192 as part of your PR.

@erictraut fantastic, thank you!

2021-12-03 02:30 UTC, erictraut commented
I published pyright 1.1.192, which contains this change. You should be able to update `workflows/tests.yml` and `tests/pyright_test.py` to point to the new version of pyright. Search for "1.1.187", which is the version that's currently used in typeshed.

2021-12-03 08:13 UTC, AlexWaygood commented
> I published pyright 1.1.192, which contains this change. You should be able to update `workflows/tests.yml` and `tests/pyright_test.py` to point to the new version of pyright. Search for "1.1.187", which is the version that's currently used in typeshed.

The pyright tests are now green 🥳🥳

2021-12-03 10:17 UTC, Akuli approved these changes
I'm a bit surprised that stubtest didn't warn about this. Maybe it is because stubtest is based on mypy, and mypy special-cases this?

2021-12-03 10:26 UTC, AlexWaygood commented
> I'm a bit surprised that stubtest didn't warn about this. Maybe it is because stubtest is based on mypy, and mypy special-cases this (I don't know if it does)?

Yeah it's a weird one. My prior with the `typing` module is that most of it is special-cased by type-checkers, so the standard tests may therefore be of limited use.

2021-12-03 10:37 UTC, srittau requested changes

2021-12-03 10:37 UTC, srittau commented on stdlib/typing.pyi
> +        __supertype__: type
This also has `__or__` and `__ror__` methods which we should include.

2021-12-03 10:38 UTC, hauntsaninja commented
It's allowlisted: https://github.com/python/typeshed/blob/1fa1270e00bd6ce351cf3a02ed785df9a8c17176/tests/stubtest_allowlists/py3_common.txt#L246

Fwiw, I'm -0 on this change (aka I don't really mind it, but I won't hit "merge" myself).

This wasn't obvious to me when I first started contributing to typeshed, but I've come to conclude that trying to stub things in typing.py accurately is just fraught (not necessarily relevant to this PR):
1) type checkers special case the hell out of most of these defs, so it doesn't accomplish much
1a) often changes just cause churn for type checkers whose special casing is now broken, as above
2) typing.py internals have historically been extremely prone to change
3) there have been cases where changing things in typing.py can cause worse errors for users
3a) more accurate stubs can cause confusion for some enterprising users who use stub definitions to conclude things about type checker behaviour for typing.py constructs
4) analysing typing.pyi is on the critical path for any type checking operation, so keeping things simple is nice

2021-12-03 10:46 UTC, hauntsaninja commented
Oh actually I take it back. The addition of `__supertype__` here seems useful.

2021-12-03 10:47 UTC, AlexWaygood commented
> Fwiw, I'm -0 on this change (aka I don't really mind it, but I won't hit "merge" myself).

Yeah, I get all that. I still think this change would be nice, as a relatively pain-free way to get the stubs closer to their runtime implementation.

2021-12-03 10:50 UTC, AlexWaygood commented
I am Unsure whether `__or__` should be typed like this  (does this even make sense???);

```python
def __or__(self: Self, other: Type[_T) -> Type[Union[Self, Type[_T]]]: ...
```

Or, more simply, like this:

```python
def __or__(self, other: type) ->_SpecialForm: ...
```

...Thoughts?

2021-12-03 10:52 UTC, srittau commented
> This wasn't obvious to me when I first started contributing to typeshed, but I've come to conclude that trying to stub things in typing.py accurately is just fraught (not necessarily relevant to this PR):
> 
> 1. type checkers special case the hell out of most of these defs, so it doesn't accomplish much
>    1a) often changes just cause churn for type checkers whose special casing is now broken, as above

I see the primary benefit of accurate types in `typing.pyi` not for type checkers, but other tools, like code completion or other, unknown uses. So all things being equal I prefer accurate types over non-accurate types in `typing.pyi`.

2021-12-03 10:53 UTC, hauntsaninja commented
Actually, it might be nice to make this unconditionally a class, since older Pythons have the `__supertype__` attribute as well.

2021-12-03 10:58 UTC, AlexWaygood commented
> Oh actually I take it back. The addition of `__supertype__` here seems maybe useful.

The `__or__` and `__ror__` methods are also important, as otherwise `NewType` can't be used in PEP 604 union-type expressions. This was the original motivation for changing the implementation of `NewType` in 3.10 (making it kind of hilarious that I left them out of the first draft of the PR).

2021-12-03 11:10 UTC, hauntsaninja commented
At least for mypy, or / ror get special cased. E.g., PEP 604 works with future annotations before 3.10 despite no typeshed or / ror.

2021-12-03 11:14 UTC, AlexWaygood commented
> At least for mypy, or / ror get special cased.

Not so for PyCharm, if memory serves correctly (though that might have changed since I last used it)

2021-12-03 11:31 UTC, hauntsaninja commented on stdlib/typing.pyi
> +        def __or__(self, other: Any) -> _SpecialForm: ...
ror :-)

2021-12-03 11:32 UTC, AlexWaygood commented on stdlib/typing.pyi
> +        def __or__(self, other: Any) -> _SpecialForm: ...
Dammit

2021-12-03 11:32 UTC, AlexWaygood commented
> I am Unsure whether `__or__` should be typed like this (does this even make sense???):
> 
> ```python
> def __or__(self: Self, other: Type[_T]) -> Type[Union[Self, Type[_T]]]: ...
> ```
> 
> Or, more simply, like this:
> 
> ```python
> def __or__(self, other: type) -> _SpecialForm: ...
> ```
> 
> ...Thoughts?

I went for the simpler option, on the assumption that it's all special-cased to some extent by type-checkers anyway, and because it's more similar to `type.__or__`. I changed the parameter type to `Any`, though, as I realised the other object doesn't _have_ to be a type — it could be another `NewType`, or a `TypeVar`, or quite a few things really.

2021-12-03 11:37 UTC, srittau approved these changes

2021-12-03 12:33 UTC, merged

2021-12-03 12:39 UTC, AlexWaygood commented
Thanks for your help, all! 🎉