stdlib: Add several missing `@abstractmethod` decorators
python/typeshed pull request #7443
Opened 2022-03-05 14:20 UTC by AlexWaygood

The following methods are all abstract at runtime, but not in the stub:

- `typing.ContextManager.__exit__` (and therefore also `contextlib.AbstractContextManager.__exit__`)
- `typing.AsyncContextManager.__aexit__` (and therefore also `contextlib.AbstractAsyncContextManager.__aexit__`)
- `numbers.Complex.__eq__`
- `numbers.Complex.__abs__`
- `numbers.Complex.__conjugate__`
- `os.PathLike.__fspath__`

This means that inheriting from any of these classes at runtime without overriding these methods would cause an exception to be raised. Type checkers, however, would not have flagged the possibility of an exception being raised, believing these methods to be concrete.

2022-03-05 18:07 UTC, AlexWaygood commented on stdlib/multiprocessing/synchronize.pyi
> -class Event(AbstractContextManager[bool]):
This class doesn't seem to be a context manager at runtime, and doesn't seem to have ever been a context manager at runtime.

2022-03-06 23:35 UTC, JelleZijlstra requested changes

2022-03-06 23:35 UTC, JelleZijlstra commented on stdlib/contextlib.pyi
> +        ) -> bool | None: ...
It actually always returns bool (on main at least), but I don't think that really matters. If we change this we have to change it above on line 131 too.

2022-03-06 23:35 UTC, JelleZijlstra commented on stdlib/mmap.pyi
> +        self, exc_type: type[BaseException] | None, exc_val: BaseException | None, exc_tb: TracebackType | None
```suggestion
        self, *args: object
```
It just ignores its arguments.

2022-03-06 23:35 UTC, JelleZijlstra commented on stdlib/mmap.pyi
> +    ) -> bool | None: ...
```suggestion
    ) -> None: ...
```
This can matter because it means the CM will never swallow exceptions.

2022-03-06 23:35 UTC, JelleZijlstra commented on stdlib/multiprocessing/synchronize.pyi
> +    ) -> bool | None: ...
```suggestion
    def __exit__(
        self, __exc_type: type[BaseException] | None, __exc_val: BaseException | None, __exc_tb: TracebackType | None
    ) -> None: ...
```
It takes *args at runtime, but those ultimately get forwarded to `_multiprocessing.SemLock.__exit__` (defined in semaphore.c), which does take exactly three arguments.

It always returns None unless you pass in a very exotic kind of lock.

2022-03-06 23:35 UTC, JelleZijlstra commented on stdlib/multiprocessing/synchronize.pyi
> +        self, exc_type: type[BaseException] | None, exc_val: BaseException | None, exc_tb: TracebackType | None
```suggestion
        self, __exc_type: type[BaseException] | None, __exc_val: BaseException | None, __exc_tb: TracebackType | None
```
As above

2022-03-06 23:35 UTC, JelleZijlstra commented on stdlib/multiprocessing/synchronize.pyi
> +    ) -> bool | None: ...
```suggestion
    ) -> None: ...
```

2022-03-06 23:35 UTC, JelleZijlstra commented on stdlib/os/__init__.pyi
> +    ) -> bool | None: ...
```suggestion
    def __exit__(
        self, *args: object
    ) -> None: ...
```
This is `ScandirIterator_exit` in posixmodule.c. It ignores its args and always returns None.

2022-03-07 00:01 UTC, AlexWaygood commented
> Diff from [mypy_primer](https://github.com/hauntsaninja/mypy_primer), showing the effect of this PR on open source code:
> 
> ```diff
> pandera (https://github.com/pandera-dev/pandera)
> - pandera/checks.py:74: error: Argument 1 to "ChainMap" has incompatible type "MappingProxyType[str, Any]"; expected "MutableMapping[str, Callable[..., Any]]"  [arg-type]
> - pandera/model.py:362: error: Need type annotation for "attrs" (hint: "attrs: Dict[<type>, <type>] = ...")  [var-annotated]
> 
> pydantic (https://github.com/samuelcolvin/pydantic)
> - pydantic/class_validators.py:332: error: Need type annotation for "all_attributes"  [var-annotated]
> - pydantic/class_validators.py:332: error: Argument 1 to "ChainMap" has incompatible type "*List[MappingProxyType[str, Any]]"; expected "MutableMapping[<nothing>, <nothing>]"  [arg-type]
```

These are weird -- looks like this crossed the streams with #7423 being merged, maybe?

2022-03-07 00:02 UTC, JelleZijlstra commented
The boostedblob errors are unfortunate. They're in places like https://github.com/hauntsaninja/boostedblob/blob/eb6e95b41ba55c4c595cbe754d05a48f069ce42e/boostedblob/path.py#L328, where `request.execute` is an async CM. The new annotations make mypy catch on to the fact that async CMs can eat exceptions.

And yeah, not sure what caused the ChainMap changes.

2022-03-07 00:03 UTC, JelleZijlstra commented
Oh wait, I bet mypy special cases `-> bool` as "may swallow" and assumes that "bool | None" means "won't swallow". So we should probably just change `_AsyncGeneratorContextManager.__exit__` back; sorry for the thrash.

2022-03-07 00:10 UTC, JelleZijlstra commented
And now pyright in CI is complaining about shutil, which you didn't change.

2022-03-07 00:10 UTC, JelleZijlstra approved these changes

2022-03-07 00:12 UTC, AlexWaygood commented
> And now pyright in CI is complaining about shutil, which you didn't change.

Yeah, it's because https://github.com/python/typeshed/pull/7384 made `chown` unavailable on Windows, but it's still declared in `__all__` on Windows. It wasn't picked up by CI running on the PR, because I increased pyright strictness for checking `__all__` after the PR was filed.

2022-03-07 00:27 UTC, JelleZijlstra commented
Ah good catch

2022-03-07 00:41 UTC, merged