Add types to invoke.Runner.run
python/typeshed pull request #8279
Opened 2022-07-12 14:07 UTC by kasium

2022-07-12 14:40 UTC, AlexWaygood requested changes
Thanks! A few points below.

As well as the things I've mentioned below:
- We generally prefer to use protocols for I/O types, rather than concrete classes. I haven't done a deep investigation into the source code, but it looks like `_typeshed.SupportsWrite` and might work well for `in_stream` and `out_stream`. Could you maybe take a look?

2022-07-13 07:12 UTC, kasium commented
So, invoke uses sys.stdout/stderr by default for streams and they have TextIO as their type I would like to use them

2022-07-13 07:12 UTC, kasium commented on stubs/invoke/invoke/runners.pyi
> +        env: dict[str, str] = ...,
done

2022-07-13 07:19 UTC, kasium commented
Can you please check the overload? In short:

- if disown is True-> return None (asynchronous is ignored)
- if asynchronous is True and disown is False or default -> return Promise
- if asynchronous is False or default and disown is False or default  -> return Result

2022-07-13 07:59 UTC, AlexWaygood commented on stubs/invoke/invoke/runners.pyi
> +from typing import Any, overload
```suggestion
from typing import Any, TextIO, overload
```

2022-07-13 08:04 UTC, AlexWaygood commented
> Can you please check the overload? In short:
> 
> * if disown is True-> return None (asynchronous is ignored)
> * if asynchronous is True and disown is False or default -> return Promise
> * if asynchronous is False or default and disown is False or default  -> return Result

I've taken the liberty of pushing to your branch to fix various things. Could you take another look and check that everything looks okay from your end?

2022-07-13 08:25 UTC, kasium commented
wow, thanks a lot! Looks great

2022-07-13 08:28 UTC, AlexWaygood approved these changes
Great, thank you!

2022-07-13 08:29 UTC, merged