ssl, socket, array: Improve bytes handling
python/typeshed pull request #8997
Opened 2022-10-27 13:51 UTC by JelleZijlstra

2022-10-27 13:57 UTC, JelleZijlstra commented on stdlib/_socket.pyi
> +_Address: TypeAlias = tuple[Any, ...] | str | ReadableBuffer
All uses of this alias in the socket stubs allow a ReadableBuffer, so I put ReadableBuffer in the alias and removed explicit usage of bytes below.

The alias is used in some other stubs, but we can review those in a different PR.

2022-10-27 13:57 UTC, JelleZijlstra commented on stdlib/array.pyi
> +    def __init__(self: array[int], __typecode: _IntTypeCode, __initializer: bytes | bytearray | Iterable[int] = ...) -> None: ...
bytes and bytearray specifically are treated differently. Arbitrary non-iterable buffers (e.g., `pickle.PickleBuffer`) don't work.

2022-10-27 13:57 UTC, JelleZijlstra commented on stdlib/socket.pyi
> +    host: bytes | str | None,
It explicitly accepts only bytes, not bytearray.

2022-10-27 13:57 UTC, JelleZijlstra commented on stdlib/ssl.pyi
> +_PasswordType: TypeAlias = Union[Callable[[], str | bytes | bytearray], str, bytes, bytearray]
The handling code handles bytes and bytearray, but not arbitrary buffers.

2022-10-27 13:57 UTC, JelleZijlstra commented on stdlib/ssl.pyi
> +if sys.version_info < (3, 12):
Noticed this one is gone in 3.12.

2022-10-27 13:57 UTC, JelleZijlstra commented on stdlib/ssl.pyi
> +    @property
All these are read-only.

2022-10-28 09:58 UTC, srittau requested changes

2022-10-28 09:58 UTC, srittau commented on stdlib/_socket.pyi
> +# See getsockaddrarg() in socketmodule.c.
One more case is `bytes` only for `BTPROTO_HCI` on NetBSD, but I don't think this exotic case is worth mentioning.

2022-10-28 09:58 UTC, srittau commented on stdlib/socket.pyi
> +        source_address: _Address | ReadableBuffer | None = ...,
Since you explicitly added `ReadableBuffer` to `_Address`:

```suggestion
        source_address: _Address | None = ...,
```

2022-10-28 09:58 UTC, srittau commented on stdlib/socket.pyi
> +        source_address: _Address | ReadableBuffer | None = ...,
```suggestion
        source_address: _Address | None = ...,
```

2022-10-28 13:35 UTC, srittau approved these changes

2022-10-28 13:35 UTC, merged