Adapt number types in ast
python/typeshed pull request #9130
Opened 2022-11-08 08:57 UTC by kasium

Since mypy  0.990 type promotions was limited.
This means that complex is not longer promoted to int/float, therefore we should adapt the types to list all possible types

Closes #9129

2022-11-08 09:05 UTC, kasium commented
Mypy flake8 doesn't like it
```
./stdlib/_ast.pyi:332:12: Y041 Use "complex" instead of "float | complex" (see "The numeric tower" in PEP 484)
```

2022-11-08 09:10 UTC, ilevkivskyi commented
Well I guess we can exclude `Y041` (it is not very useful IMO), or if people still like it, you can put a `# noqa: Y041` on those lines.

2022-11-08 09:16 UTC, kasium commented
@ilevkivskyi I added a noqa for now and opened an issue at flake8-pyi

2022-11-08 10:08 UTC, AlexWaygood requested changes
I'd like to discuss this a little more before we go ahead with this. We may want to do a complete revert of #7906 if we need to go down this route.

2022-11-08 10:16 UTC, AlexWaygood commented on .flake8
> +  stdlib/typing.pyi: B, E301, E302, E305, E501, E701, E741, NQA102, F401, F403, F405, F811, F822, Y037, Y041
You'd need to add Y041 to lines 35 and 42 in this file, as well. Currently you're only ignoring Y041 in `stdlib/typing.pyi` specifically, not in any other stubs

2022-11-08 10:21 UTC, ilevkivskyi commented
I don't think we need to do a full revert. It needs to be decided on case by case basis. For example, in function argument types using promotions is OK (unless function behaves differently for `int` and `float`).

2022-11-10 21:40 UTC, hauntsaninja approved these changes
Changes to stubs look good!

2022-11-11 12:23 UTC, kasium commented
Can this please be merged?

2022-11-14 06:36 UTC, kasium commented
Hi,
can we please get this merged? Do you know when mypy will pick this up?

2022-11-14 08:05 UTC, AlexWaygood commented
Hi @kasium! The discussion in the mypy issue means that it looks like the behaviour change in mypy is about to be reverted: https://github.com/python/mypy/pull/14077. So I don't think there's a massive rush to get this merged :)

Having said that, I'm happy for the changes to the `ast` and `typed-ast` stubs to go in. The typing specs don't precisely specify how type checkers should deal with implicit promotions with respect to attribute annotations. As such, we should err on the side of  fully specified behaviour, and _not_ rely on implicit promotions for these cases over at typeshed. So the changes to the `ast` and `typed-ast` stubs look good to me.

I'd rather fix flake8-pyi first, however, so that it only emits Y041 for parameter annotations. Then we won't need to switch off Y041 in typeshed's `.flake8` config file, and this PR can be focused solely on the changes to the `ast` and `typed-ast` stub. I should be able to create a flake8-pyi fix and release at some point in the next few days.

2022-11-14 08:10 UTC, AlexWaygood commented
I've asked if there's any chance of getting a mypy patch release with python/mypy#14077 included: https://github.com/python/mypy/issues/13871#issuecomment-1313250893.

2022-11-14 09:08 UTC, AlexWaygood commented
Update: mypy doesn't want to include https://github.com/python/mypy/pull/14077 in a patch release. So let's merge this as a short-term fix.

2022-11-14 09:10 UTC, AlexWaygood approved these changes

2022-11-14 09:41 UTC, merged

2022-11-14 09:52 UTC, AlexWaygood commented
Thanks for the PR @kasium!

2022-11-14 11:30 UTC, kasium commented
Thanks for the fast work!

2022-11-14 13:22 UTC, AlexWaygood commented
@kasium — looks like the `ast` fixes will be included in the next mypy patch release, possibly coming out later today: https://github.com/python/mypy/issues/13871#issuecomment-1313680647